using Microsoft.EntityFrameworkCore;

namespace Topmovies.Models
{
    public class MovieContext : DbContext
    {
        public DbSet<Movie> Movies { get; set; }
        public MovieContext(DbContextOptions<MovieContext> options) : base(options)
        {
            if (Database.EnsureCreated())
            {
                Movies.Add(new Movie { Title = "Pixels", Genre = "Science fiction comedy film", ReleaseDate = Convert.ToDateTime("24/07/2015 12:00"), Description = "Sam has been one of the best arcade gamers of his time. Once in an international tournament NASA sent the video recording of all the games to space for intelligent beings to find and know more about humans. However the aliens interpreted the games as a challenge and began attacking Earth using the video game data. It's now up to Sam and other old time arcade game champions to save the Earth from the video game alien invasion.", PicturePath = "/Files/Pictures/pxs.jpg" });

                Movies.Add(new Movie { Title = "Wonka", Genre = "Kids & family, Fantasy, Comedy", ReleaseDate = Convert.ToDateTime("15/12/2023 12:00"), Description = "Based on the extraordinary character at the center of Charlie and the Chocolate Factory, Roald Dahl’s most iconic children's book and one of the best-selling children's books of all time, \"Wonka\" tells the wondrous story of how the world's greatest inventor, magician and chocolate-maker became the beloved Willy Wonka we know today.", PicturePath = "/Files/Pictures/wonka.jpg" });

                Movies.Add(new Movie { Title = "Wish", Genre = "Kids & family, Fantasy, Adventure, Comedy, Animation, Musical", ReleaseDate = Convert.ToDateTime("22/11/2023"), Description = "Walt Disney Animation Studios' \"Wish\" is an all-new musical-comedy welcoming audiences to the magical kingdom of Rosas, where Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force--a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe--the ruler of Rosas, King Magnifico--to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.", PicturePath = "/Files/Pictures/wish.jpeg" });

                Movies.Add(new Movie { Title = "Napoleon", Genre = "Biography, History, Drama, War, Action", ReleaseDate = Convert.ToDateTime("21/11/2023 11:00"), Description = "\"Napoleon\" is a spectacle-filled action epic that details the checkered rise and fall of the iconic French Emperor Napoleon Bonaparte, played by Oscar winner Joaquin Phoenix. Against a stunning backdrop of large-scale filmmaking orchestrated by legendary director Ridley Scott, the film captures Bonaparte's relentless journey to power through the prism of his addictive, volatile relationship with his one true love, Josephine, showcasing his visionary military and political tactics against some of the most dynamic practical battle sequences ever filmed.", PicturePath = "/Files/Pictures/napoleon.jpeg" });

                Movies.Add(new Movie { Title = "Aquaman And The Lost Kingdom", Genre = "Action, Adventure, Fantasy", ReleaseDate = Convert.ToDateTime("20/10/2023 12:00"), Description = "After failing to defeat Aquaman the first time, Black Manta wields the power of the mythic Black Trident to unleash an ancient and malevolent force. Hoping to end his reign of terror, Aquaman forges an unlikely alliance with his brother, Orm, the former king of Atlantis. Setting aside their differences, they join forces to protect their kingdom and save the world from irreversible destruction.", PicturePath = "/Files/Pictures/aqua.jpg" });

                Movies.Add(new Movie { Title = "Oppenheimer", Genre = "Movies, Biographical, Dramas", ReleaseDate = Convert.ToDateTime("20/07/2023 12:00"), Description = "The plot of the war film called \"Oppenheimer\" will tell viewers the interesting story of the great physicist, who was not only an outstanding scientist, but also an extremely curious person. His life is filled with contradictions, which have had a great influence on his current worldview. Even as a child, he was actively interested in the world around him. Then he had no idea what a great future awaited him. He was able to become one of the central figures of the Second World War. The brilliant physicist worked without rest on his greatest project. He was not afraid to put forward large-scale theories. Robert became the creator of the atomic bomb. Because of his discovery, Hiroshima and Nagasaki were practically wiped off the face of the Earth. He blamed himself for the death of these people, not realizing the approaching danger. His love for his homeland was too great to notice. The government did not reciprocate his feelings...", PicturePath = "/Files/Pictures/oppen.jpg" });

                Movies.Add(new Movie { Title = "Shrapnel", Genre = "Movies, Action, Thrillers", ReleaseDate = Convert.ToDateTime("28/07/2023 15:00"), Description = "The film tells the story of former Marine Mike and his old battle buddy Jimenez, who decide to confront the Mexican drug cartel behind the disappearance of Mike's daughter. Mike, an Iraq War veteran, lives a quiet life in Arizona with his family. But his life changes dramatically when his daughter Silva disappears in Mexico. The local police are not interested in the investigation, and Mike decides to go in search of his daughter. He turns to his old friend Jimenez, who agrees to help him.", PicturePath = "/Files/Pictures/sharp.jpg" });

                Movies.Add(new Movie { Title = "Day Shift", Genre = "Comedy, Action ,Horror", ReleaseDate = Convert.ToDateTime("12/08/2022 16:00"), Description = "In the comedy horror film “Day Shift,” the main character never dreamed that he would become a hunter of bloodthirsty evil spirits. All his life he didn’t even believe in the existence of ghouls. One day everything changed dramatically. Now they pay decent money for the extermination of these blood lovers, which in his position will not be superfluous. He has been raising his 8-year-old daughter on his own for a long time and tries to give her everything she needs.", PicturePath = "/Files/Pictures/shift.jpg" });

                Movies.Add(new Movie { Title = "To Nowhere", Genre = "Dramas, Thrillers", ReleaseDate = Convert.ToDateTime("29/11/2023 18:00"), Description = "Mia lived an ordinary life and was preparing for the birth of her first child, until the situation in the country changed dramatically. A civil uprising began, causing constant shootings. The girl understood that in such an atmosphere the child could suffer, so she decided to leave the country. But all borders were closed, only a friend advised me to go to the port and negotiate with the sailors to be allowed into one of the containers. Mia did so, but the soldiers found out about this and began to take everyone out. The main character received a blow to the head after which she lost consciousness, and came to her senses when the ship was at sea. At this time, a storm was raging and many containers ended up overboard. The water began to fill, the girl began to panic, she did not understand what to do, because very soon she would die. But this was only the beginning, because contractions had already begun.", PicturePath = "/Files/Pictures/nowh.jpg" });

                Movies.Add(new Movie { Title = "Blade Runner 2049", Genre = "Science Fiction, Thrillers", ReleaseDate = Convert.ToDateTime("05/10/2017 12:00"), Description = "In the near future, people peacefully coexist with robots - replicants. The latter are superior to humans in many respects - endurance, physical strength, mental development. Only emotions are beyond their control, but robots are actively used in dangerous industries, as well as in prostitution. The number of replicants is controlled; once every four years, a program is launched that leads to the death of the robot. They do not agree with this state of affairs, because in essence they are slaves of people, those who are much weaker than them. Periodically there are uprisings, robots escape to try to avoid death. A real hunt is organized for the fugitives by specially trained people. Blade runners are the name given to those who catch replicants - fugitives. It is quite difficult to distinguish a person from an android.", PicturePath = "/Files/Pictures/run.jpg" });

                SaveChanges();
            }
        }
    }
}
